# vim: ts=2 sw=2

name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v12
    - name: Cache nix environment
      run: nix-shell -I nixpkgs=channel:nixos-19.09 --run "exit 0"
    - name: Build target and test
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build -j
        cd build
        ctest --timeout 120 -T memcheck
        [[ -z $(cat Testing/Temporary/MemoryChecker.*.log) ]]
      shell: env nix-shell -I nixpkgs=channel:nixos-19.09 --run "bash -e {0}"
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: fail-logs
        path: build/Testing/Temporary
